import type { PSPProvider } from '../types';

export const providers: PSPProvider[] = [
  {
    id: 'visa-acceptance',
    name: 'Visa Acceptance Solutions',
    logo: '/logos/visa.png',
    statusPageUrl: 'https://status.visaacceptance.com',
    apiType: 'statuspage_io',
    apiBaseUrl: 'https://status.visaacceptance.com/api/v2',
    category: 'Card Network',
    region: 'Global',
  },
  {
    id: 'mastercard',
    name: 'Mastercard',
    logo: '/logos/mastercard.svg',
    statusPageUrl: 'https://developer.mastercard.com/api-status',
    apiType: 'custom',
    apiBaseUrl: import.meta.env.DEV
      ? '/proxy/mastercard'
      : 'https://developer.mastercard.com',
    category: 'Card Network',
    region: 'Global',
    corsProxy: true,
  },
  {
    id: 'paypal',
    name: 'PayPal',
    logo: '/logos/paypal.png',
    statusPageUrl: 'https://www.paypal-status.com',
    apiType: 'custom',
    apiBaseUrl: import.meta.env.DEV
      ? '/proxy/paypal/api'
      : 'https://www.paypal-status.com/api',
    category: 'Wallet / PSP',
    region: 'Global',
    corsProxy: true,
  },
  {
    id: 'klarna',
    name: 'Klarna',
    logo: '/logos/klarna.svg',
    statusPageUrl: 'https://status.klarna.com',
    apiType: 'statuspage_io',
    apiBaseUrl: 'https://status.klarna.com/api/v2',
    category: 'BNPL',
    region: 'EU / Global',
  },
  {
    id: 'googlepay',
    name: 'Google Pay',
    logo: '/logos/googlepay.svg',
    statusPageUrl: 'https://pay.google.com/status/',
    apiType: 'custom',
    apiBaseUrl: 'https://pay.google.com/status',
    category: 'Wallet / PSP',
    region: 'Global',
  },
  {
    id: 'applepay',
    name: 'Apple Pay',
    logo: '/logos/applepay.svg',
    statusPageUrl: 'https://www.apple.com/support/systemstatus/',
    apiType: 'custom',
    apiBaseUrl: import.meta.env.DEV
      ? '/proxy/apple'
      : 'https://www.apple.com',
    category: 'Wallet / PSP',
    region: 'Global',
    corsProxy: true,
  },
  {
    id: 'unzer',
    name: 'Unzer',
    logo: '/logos/unzer.png',
    statusPageUrl: 'https://status.unzer.com',
    apiType: 'statuspage_io',
    apiBaseUrl: 'https://status.unzer.com/api/v2',
    category: 'Payment Gateway',
    region: 'EU',
  },
  {
    id: 'eps',
    name: 'EPS',
    logo: '/logos/eps.svg',
    statusPageUrl: 'https://eservice.psa.at/de/eservice-status.html',
    apiType: 'custom',
    apiBaseUrl: import.meta.env.DEV
      ? '/proxy/eps'
      : 'https://eservice.psa.at',
    category: 'Online Banking (AT)',
    region: 'Austria',
    corsProxy: true,
  },
  {
    id: 'payone',
    name: 'PAYONE',
    logo: '/logos/payone.svg',
    statusPageUrl: 'https://www.payone.com/AT-de/service/aktuelle-stoerung',
    apiType: 'custom',
    apiBaseUrl: 'https://api.storyblok.com/v2/cdn',
    category: 'Payment Gateway',
    region: 'AT / EU',
  },
  {
    id: 'worldline',
    name: 'Worldline',
    logo: '/logos/worldline.svg',
    statusPageUrl: 'https://wlop.status.worldline-solutions.com',
    apiType: 'statuspage_io',
    apiBaseUrl: 'https://wlop.status.worldline-solutions.com/api/v2',
    category: 'Payment Gateway',
    region: 'EU / Global',
  },
  {
    id: 'worldpay',
    name: 'Worldpay',
    logo: '/logos/worldpay.svg',
    statusPageUrl: 'https://worldpayforplatforms.statuspage.io',
    apiType: 'statuspage_io',
    apiBaseUrl: 'https://worldpayforplatforms.statuspage.io/api/v2',
    category: 'Full-Stack PSP',
    region: 'Global',
  },
  {
    id: 'stripe',
    name: 'Stripe',
    logo: '/logos/stripe.svg',
    statusPageUrl: 'https://www.stripestatus.com',
    apiType: 'statuspage_io',
    apiBaseUrl: 'https://www.stripestatus.com/api/v2',
    category: 'Full-Stack PSP',
    region: 'Global',
  },
  {
    id: 'square',
    name: 'Square',
    logo: '/logos/square.svg',
    statusPageUrl: 'https://issquareup.com',
    apiType: 'statuspage_io',
    apiBaseUrl: 'https://issquareup.com/api/v2',
    category: 'Full-Stack PSP',
    region: 'US / Global',
  },
  {
    id: 'cybersource',
    name: 'CyberSource',
    logo: '/logos/cybersource.svg',
    statusPageUrl: 'https://status.cybersource.com',
    apiType: 'statuspage_io',
    apiBaseUrl: 'https://status.cybersource.com/api/v2',
    category: 'Payment Gateway (Visa)',
    region: 'Global',
  },
  {
    id: 'adyen',
    name: 'Adyen',
    logo: '/logos/adyen.svg',
    statusPageUrl: 'https://status.adyen.com',
    apiType: 'custom',
    apiBaseUrl: import.meta.env.DEV
      ? '/proxy/adyen/api'
      : 'https://status.adyen.com/api',
    category: 'Full-Stack PSP',
    region: 'EU / Global',
    corsProxy: true,
  },
  {
    id: 'worldpay-gateway',
    name: 'Worldpay Gateway',
    logo: '/logos/worldpay.svg',
    statusPageUrl: 'https://status.worldpay.com',
    apiType: 'statuspage_io',
    apiBaseUrl: 'https://status.worldpay.com/api/v2',
    category: 'Payment Gateway',
    region: 'Global',
  },
];
